version: '3.1'

services:
    mongo:
        image: mongo
        restart: always
        
        command: [--smallfiles]
    server:
        container_name: playapp
        build: .
        command: make run
        environment:
            - DB_HOST=mongo
        volumes:
            - .:/code
        
        ports:
            - "9090:9000"
        depends_on:
            - mongo
